include: package:pedantic/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: false
    unawaited_futures: false
    
exclude:
  - '**/*.g.dart'
  - '**/generated/*.dart'
  - '**/*.mocks.dart'
  - '**/*.config.dart'
  - '**/*.freezed.dart'
